baseURL: "https://rahulkc.com"
languageCode: "en-us"
title: "Rahul Kanianchalil"
theme: hugo-profile

Paginate: 3
disqusShortname:
googleAnalytics:

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
    
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2

params:
  title:
  description: My personal site for hosting projects and sharing updates
  # staticPath: ""  # The path to serve the static files from
  favicon:

  theme:
    disableThemeToggle: false
    defaultTheme: "dark"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Rahul Kanianchalil."
    subtitle: "Softwar Engineer, Gamer, Car Enthusiast, Traveler."
    content: "Welcome to my site! Come take a look at what I've been working on!"
    image: /images/rahul.jpeg
    button:
      enable: false
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/rkanianchalil/
        - icon: fab fa-github
          url: https://github.com/rkania3
        # - icon: fab fa-mobile
        #   url: https://example.com
      content: "hi"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/terminal.svg"
    content: |-
      Engineering professional with a strong focus on data driven innovation and a demonstrated history of applying the principles of design thinking, rapid prototyping, and customer focus to deliver desirable products.

    skills:
      enable: true
      title: 
      items:
        - "AWS"
        - "Python"
        - "Java"
        - "Backend Engineering"
        - "Devops Engineering"

  # Experience
  experience:
    enable: true
    items:
      - job: "Senior Software Engineer"
        company: "Katapult"
        companyUrl: "https://katapult.com"
        date: "Aug 2021 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "TODO"

      - job: "Associate Software Engineer"
        company: "Capital One"
        companyUrl: "https://capitalone.com"
        date: "Sep 2017 - Aug 2021"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: 
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "Intern Software Engineer"
        company: "State Farm"
        companyUrl: "https://statefarm.com"
        date: "Jun 2016 - Dec 2016"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "University of Illinois at Urbana Champaign"
        school:
          name: "Bachelor of Science in Statistics"
        date: "2013 - 2017"
        content: |-
          Extracurricular Activities:
            - Association of Data Science And Analytics
            - Research Lab Assistant
      - title: "Libertyville High School"
        date: "2009-2013"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: Feel free to contact me with job opportunities or to collaborate on projects!
    email: rahul.kc1@gmail.com
    btnName: Send Mail

  footer:
    recentPosts: false
    # socialNetworks:
    #   github: https://github.com
    #   linkedin: https://linkedin.com
    #   twitter: https://twitter.com
    #   instagram: https://instagram.com
    #   facebook: https://facebook.com
